from Metodos.metodos import Fraccionario

"""print("Fraccion 1")
print("Ingrese numerador")
num1=input()
num1=int(num1)
print("Ingrese Denominador")
den1=input()
den1=int(den1)
print("Fraccion 2")
print("Ingrese numerador")
num2=input()
num2=int(num2)
print("Ingrese Denominador")
den2=input()
den2=int(den2)
f1 = Fraccionario(num1,den1)
f2 = Fraccionario(num2,den2)"""
f1 = Fraccionario(1,3)
f2 = Fraccionario(2,4)

print(f1.imprimir())
print (f2.imprimir())
#print (f1.esHomogenea(f2))
#print (f1.suma(f2).imprimir())
#f1.invertir()
#print(f1.esPositiva())
#print(f1.valorFraccion())
#print(f1.multiplicacion(f2).imprimir())